### ISSUE TITLE
Sprint wrap-up blog post

### ISSUE THREAD

**Issue by nuest** [minrk/jupyter-dar#12]
I'd like to write a little wrap-up blog post with the stuff started at the sprint, probably not including the ideas going beyond that (discussed on Gitter during sprint), with the following content (feedback welcome)

## TASKS

- [x] https://github.com/jupyter/repo2docker/pull/457 must be merged
- [x] https://github.com/jupyterhub/mybinder.org-deploy/pull/843 must be merged for changes to be deployed to mybinder.org
- [x] Move Stencila examples to https://github.com/binder-examples
  - [x] Python: https://github.com/nuest/stencila-py
  - [x] R: https://github.com/nuest/stencila-r
- [x] Add example links / badges to blog post

## Blog post content

**Draft: https://github.com/minrk/nbstencilaproxy/issues/12#issuecomment-435974747**

- [x] what is Jupyter/Binder/Dar/Stencila?
- [x] why is it useful to integrate them? use cases!
- [x] what were the steps to integrate them (see README.md)
  - [x] **README.md must be updated!** See the closed PR how this now actually works: https://github.com/jupyter/repo2docker/pull/309
- [x] demo articles snippets for different languages are available in the repo2docker tests, see https://github.com/jupyter/repo2docker/tree/master/tests/stencila/basic/archive
- [x] what is required for a user's repo to work, see https://github.com/nuest/stencila-py and https://github.com/nuest/stencila-r
- [x] next steps

## Publication & post-publication

It would be cool if the article could be cross-posted:

- [x] https://stenci.la/blog/ - https://stenci.la/blog/2018-11-20-stencila-binder/
- [ ] https://blog.jupyter.org/
- [x] https://o2r.info - https://o2r.info/2018/11/21/elife-sprint-integrating-stencila-and-binder/
- [x] https://elifesciences.org/labs > https://elifesciences.org/labs/d42fe2b9/integrating-binder-and-stencila-the-building-blocks-to-increased-open-communication-and-transparency
- [x] Tweets
- [x] post link in https://community.stenci.la/t/stencila-in-binder/142
- [x] post link in https://github.com/mozilla/global-sprint/issues/317
- [x] annotate on https://elifesciences.org/labs/bdd4c9aa/elife-innovation-sprint-2018-project-roundup#annotations

**Comment by npscience** [comment]
We might be interested to cross-post too, on eLife Labs: https://elifesciences.org/labs - let me know if that's of interest to you.

**Comment by nokome** [comment]
I'm happy to help with a post and we'd certainly love to cross-post it on the Stencila blog. Pinging @apawlik

**Comment by nuest** [comment]
First post already published on Stencila blog: http://stenci.la/blog/2018-05-stencila-in-binder/

I think we're getting closer to having enough for a second post with R and Python working!

**Comment by apawlik** [comment]
Absolutely! I'm up for it and happy to help!

**Comment by npscience** [comment]
@nuest I'll link to the current post from the eLife blogs soon

A post with R and Python working too would be fab. We'd be interested to publish this on Labs as a report of the project you worked on at the Sprint.

@apawlik @nokome would you be happy with cross-posting if this is what Daniel and Min do? (If only the WWW worked as first dreamt and we could be channels to the same page instead of copying over :( )

**Comment by nokome** [comment]
> would you be happy with cross-posting if this is what Daniel and Min do?

@npscience : absolutely! The initial post linked to above was just intended as a short bit of news. A lengthier post by Daniel and Min would be great and we'd cross post it for sure.

I'd like to suggest that the post could be written in Markdown and then converted to JATS using [stencila-convert](https://github.com/stencila/convert), or written using Stencila Desktop directly. It could then be used as the 'landing page' when you click the "Open in Binder" button - complete with R, Python and iPython code cells.

**Comment by npscience** [comment]
It would be very meta if the post could be a Stencila doc that could launch in Binder!
 @nuest is there a sensible reason why a reader might want to run some of the code themselves?

For the blogsite, this is separate to our journal and doesn't use JATS nor does it support anything fancy (not even import from GDocs yet) so I would have to do a little legwork to get a static version up on Labs, and then have a link to launch the executable one in Binder. Note we can't hyperlink an image yet either, so can't use traditional Binder button. I'm happy to do the legwork, it'll just take a little longer from your desk(s) to the eLife Labs page.

However, these are excellent examples to motivate continued development of our blogsite, I'll pass the suggestions on / check their progress in the backlog.

**Comment by npscience** [comment]
Hello @nuest — I was wondering if you had a timeframe in mind for the detailed blogpost about this work? I'd love to find you a good spot in our schedule.

**Comment by nuest** [comment]
Thanks @npscience for following up. I like your idea of the blog post being a Stencila doc :-) But I agree the actual posts should be a static site (our blog uses R Markdown) mirroring the Stencila document on Binder, and including the "fixed" code cells, which are naturally not editable in the blog, but then become interactive when opening the article on Binder!

Can you explain what you mean with "run the code themselves"? I am not sure how I pointed at that. The Stencila doc should include some example code snippets, but they would "run" on Binder.

The "blocker" for the blog post is https://github.com/jupyter/repo2docker/pull/309 - @minrk let's continue there!

**Comment by npscience** [comment]
Hi @nuest - it was @nokome's idea to write the post in Stencila, and whilst I support it I wanted to make sure it was clear that our blogsite wouldn't support anything fancy: we would need a static post to publish on Labs. We can't read in .rmd files to our blogsite, but it's fine if you want to write it that way, I'll just need a little time to port the content across to the blogsite. We can replicate code block styling, so it shouldn't make much difference in terms of the content you might wish to display. And for any interactive / executable content, we can link out (i.e. with a Binder link).

Please just let me know when you have a draft ready, and I'll get it into our schedule. Many thanks!

**Comment by npscience** [comment]
Hello -- just to say that if you'd like to share a post via eLife Labs, please email innovation [at] elifesciences [dot] org when you're ready.

Hope all is going well! -- Naomi

**Comment by nuest** [comment]
Thanks for the reminder, though the occasion also is a bit sad (you're wrapping up stuff at eLife, I guess). I'll poke @minrk with some questions and updated the outline in the first comment, feedback welcome! Expect a draft for a blog post in the next few weeks.

**Comment by nuest** [comment]
Made some progress with testing and updates:

- https://github.com/stencila/stencila/issues/727
- https://github.com/nuest/stencila-py
- https://github.com/nuest/stencila-r
- https://github.com/jupyter/repo2docker/pull/457

**Comment by nuest** [comment]
@npscience @nokome @minrk Feedback for blog post welcome: https://github.com/nuest/o2r-project.github.io/blob/elife-blog/_drafts/elife-sprint-integrating-stencila-and-binder.md

I'd be happy to have shortened versions as appropriate for the different audiences, in case you're still considering cross-posting!

**Comment by nuest** [comment]
Current status: js-mini-sql - Example is under development, deployment of updated repo2docker to mybinder.org is in the queue..

**Comment by nuest** [comment]
The example repos are transferred to binder-examples org, and everything works nicely. The **final blog post draft** is now available at

https://github.com/nuest/o2r-project.github.io/blob/elife-blog/_drafts/elife-sprint-integrating-stencila-and-binder.md

I will reach out to @nokome, elife and Jupyter about potential publications on blogs.

**Comment by nuest** [comment]
Three blog posts are published now, see links in first comment - I declare this issue closed!
